specVersion: 1.0.0
name: parascan-polkadot
version: 0.0.1
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: ""
repository: https://github.com/jamesbayly/parascan-polkadot
schema:
  file: ./schema.graphql
network:
  chainId: "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3"
  endpoint:
    [
      "https://polkadot.api.onfinality.io/rpc?apikey=46760238-642b-45e5-b7ff-06050358144a",
      "wss://rpc.polkadot.io",
    ]
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
